### ISSUE TITLE
global: Extended Date/Time Format (EDTF) support

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-formatter#16]
Add utilities to work with dates/times in EDTF format: http://www.loc.gov/standards/datetime/pre-submission.html
- Validation of EDTF
- Localisation of a EDTF (display)

Some prior work in:
- https://github.com/ixc/python-edtf
- https://github.com/unt-libraries/edtf-validate

**Comment by kaplun** [comment]
This is quite interesting. 

On Invenio legay we had to implement something related in order to implement the concept of `earliest_date`, i.e. the earliest possible known date among all those available in the metadata.

Say that year of publication was 1983, but preprint date is 1983-03-23, then with a naïve algorithm one would consider as earliest date for the record 1983-01-01. However the most accurate thing we could actually say is indeed `1983-03-23` since it's compatible with the publication year unprecise information.

See: https://github.com/inspirehep/invenio/blob/prod/modules/bibcheck/lib/plugins/earliest_date.py

**Comment by lnielsen** [comment]
Implemented in Babel-EDTF as well as Marshmallow-Utils.
